### ISSUE TITLE
ddsp V1.6.0 not compatible with Dplug 7.0.5

### ISSUE THREAD

**Issue by rstephane** [ctrecordings/Ddsp#17]
Dear ctrecordings :)
I am trying to fetch your lib into the lastest version of Dplug (7.0.5). I got errors when compiling as your curent version (looks great, by the way!) is using alignedbuffer function which is not anymore used.

Are you thinking of building a new version of ddsp that may work with Dplug 7 ? 
If I can help, tell me, I am a newbie but I could try to help :)

Regards.

**Comment by abaga129** [comment]
Hi @rstephane 
I'm glad you're interested in using ddsp!
It shouldn't require much to get it compatible with Dplug 7.0.5.  I'll try to look at it later today.  Feel free to make a pull request if you are able to get it working yourself.  I didnt realize I was still relying on alignedbuffer.  It should be replaced with `Vec!T` from dplug:core.

**Comment by rstephane** [comment]
Dear Abaga129 :)

I talked to Guillaume from Auburn Sounds and he gave me more information
- In Dplug v6, dplug.core.alignedbuffer has been renamed dplug.core.vec, but the old name and file remain in the distribution of the package.
- In Dplug v7, dplug.core.alignedbuffer has been removed , not usefull anymore.

I don't know if it can help you ? 
meanwhile I am trying to recompile on my side the lib, I have some issues due to my DUB configuration that fetch the offical package and not my local one :-( I will find out ;-)
I keep you inform.
Regards.

**Comment by abaga129** [comment]
Thanks for the info.

I was aware that alignedbuffer had been deprecated but I didnt know that dplug was already at version 7.  I've been using vec in most newer modules so there references to alignedbuffer should be minimal.  It's as simple as replacing alignedbuffer with vec wherever it appears so it shouldnt take long to fix.

After that all that's needed is to update the dependency in `dub.json`.  Like I said, I should be able to fix this later today.  I'll inform you once I'm done :)

**Comment by rstephane** [comment]
GREAT GREAT !!!

I recompiled and upgraded dub , etc. 
It seems for the moment that my comilation works .. I will try to create an exemple and tutorial during the week about Dplug and your lib , i keep you inform.
cheers !!!!!

**Comment by abaga129** [comment]
Sounds great!  I haven't had a chance to document the library very well yet so if you have any questions, feel free to email me at ctrecordingslive@gmail.com or join the dplug discord and ask away there.  Good luck
